apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 2  # Number of pods to run
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: api-gateway:latest
        imagePullPolicy: Never  # Important: tells Kubernetes not to pull from Dockerhub registry (use local Kind cluster)
        ports:
        - containerPort: 8500
        resources:
          limits:
            cpu: "0.5"    # Max 0.5 CPU cores
            memory: "512Mi"  # Max 512MB memory
          requests:
            cpu: "0.2"    # Request 0.2 CPU cores
            memory: "256Mi"  # Request 256MB memory