apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 80 # External port
      targetPort: 8500 # Container port
      nodePort: 30080 # explicit port for external network access
  type: NodePort # Exposes service externally
